### ISSUE TITLE
Creation of folders for the sounds and renaming the sound files to more generic values

### ISSUE THREAD

**Issue by Icecoptere** [Remi-hub/Twitch_spotify_integration#8]
1. Renaming of files in media folder : 

> ca_degage.mp3 to skip_sound_1.mp3
> dj-scratch.mp3 to skip_sound_2.mp3
> pas_trouve.mp3 to no_found_sound_1.mp3

2. In media folder also, create a folder skip_sounds and a folder not_found_sounds, and put the renamed files in the correct folders

3. Update the references to those previous files in the code :
  For example : ca_degage.mp3 will become skip_sounds/skip_sound_1.mp3

**Comment by Deeeeksha** [comment]
Hello @Icecoptere I want to solve this issue.

**Comment by Icecoptere** [comment]
Awesome thanks for your interest ! Do you need any more info for it ?

**Comment by Deeeeksha** [comment]
@Icecoptere  Can you please review the PR.

**Comment by Remi-hub** [comment]
thanks for this fast and good work @Deeeeksha

**Comment by Deeeeksha** [comment]
Thankyou @Remi-hub
